const horarios = [
  [
    { nome: 'Inglês', id: '' },
    { nome: 'PPBD', id: 'ddq-mrio-gym' },
    { nome: 'Matemática', id: 'dus-xyvc-gkf' },
    { nome: 'Física', id: 'osp-mchu-scw' },
    { nome: 'Filosofia', id: '' },
    { nome: 'Ed. Física', id: 'eme-zkax-dnf' },
    { nome: 'Português', id: 'crb-brvp-uoj' },
  ],
  [
    { nome: 'IMC', id: 'zqs-gywn-hst' },
    { nome: 'Biologia', id: 'jsx-ockc-bhx' },
    { nome: 'ONST', id: 'agf-fqcs-ren' },
    { nome: 'História', id: 'tsq-mkni-nud' },
    { nome: 'Química', id: 'wzd-mwxc-njx' },
    { nome: 'Geografia', id: 'kwg-bhea-okr' },
    { nome: 'Português', id: 'crb-brvp-uoj' },
  ],
  [
    { nome: 'Inglês', id: '' },
    { nome: 'Sociologia', id: 'ovi-rftz-tnt' },
    { nome: 'Matemática', id: 'dus-xyvc-gkf' },
    { nome: 'Arte', id: 'zar-bonu-xyk' },
    { nome: 'LP II', id: 'rmt-yrma-cgt' },
    { nome: 'Ed. Física', id: 'eme-zkax-dnf' },
    { nome: 'Filosofia', id: '' },
  ],
  [
    { nome: 'História', id: 'wzb-hnwo-ufh' },
    { nome: 'Biologia', id: 'jsx-ockc-bhx' },
    { nome: 'APS', id: 'npg-cviw-zda' },
    { nome: 'Geografia', id: 'pbk-fomz-vih' },
    { nome: 'Química', id: 'wzd-mwxc-njx' },
    { nome: 'Matemática', id: 'cqj-yhns-xbt' },
    { nome: 'Português', id: 'crb-brvp-uoj' },
  ],
  [
    { nome: 'Inglês', id: '' },
    { nome: 'LP II', id: 'myz-zptt-ikt' },
    { nome: 'Matemática', id: 'dus-xyvc-gkf' },
    { nome: 'Arte', id: 'zar-bonu-xyk' },
    { nome: 'Sociologia', id: 'zzm-iirq-wgh' },
    { nome: 'Física', id: 'pcv-igbb-wku' },
    { nome: 'Português', id: 'crb-brvp-uoj' },
  ],
]
